language: perl

env:
  global:
    - SOLR_SERVER=http://127.0.0.1:8983/solr/test
    - SOLR_TEST_SCHEMA_EDITS=1

services:
  - docker

before_install:
  - docker pull solr:latest
  - docker run -d -p 127.0.0.1:8983:8983 -t --name test_solr solr
  - docker exec -it --user=solr test_solr bin/solr create_core -c test
  - build-perl

matrix:
  include:
    - perl: '5.26'

install:
  - cpanm --quiet --installdeps --notest .

script:
  - perl Makefile.PL && make test
